/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
});
export const Resume = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addResume' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getResume' : IDL.Func([IDL.Text], [IDL.Opt(Resume)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
  });
  const Resume = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addResume' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getResume' : IDL.Func([IDL.Text], [IDL.Opt(Resume)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };